### ISSUE TITLE
Is it possible to display units in MB or GB?

### ISSUE THREAD

**Issue by saudiqbal** [MichaelBelgium/VPS-Monitor#1]
It would be nice to see the RAM and HDD usage in MB and GB instead of Bytes. Example: Usage: 1 690 959 872 bytes, looks wierd to read.

**Comment by MichaelBelgium** [comment]
Such conversion is simple to do:
* 1 000 000 bytes = 1 MB =>1 690 959 872 / 1 000 000 = 1 690,959 872 MB
* 1 000 000 000 bytes = 1 GB =>  1 690 959 872 / 1 000 000 000 = 1,690959872 GB

Or binary:
* 1024 bits = 1 Kb
* 1024^2 bits = 1 Mb => 1 690 959 872 / 1024^2 = 1 612, 625 Mb
* 1024^3 bits = 1 Gb => 1 690 959 872 / 1024^3 = 1,5748291015625 Gb

**Comment by saudiqbal** [comment]
It would be nice to see the details in MB or GB instead.
