### ISSUE TITLE
it doest work like in the demo 

### ISSUE THREAD

**Issue by frankeu** [MichaelBelgium/VPS-Monitor#3]
https://monitor-vps.vercel.app/

**Comment by frankeu** [comment]
**Nevermin**. i fixed it my self and added some featured:
- Add meta viewport so it will responsive on mobile device
- Add function bytes To Size (kb, mb, gb, tb)
- Add automaticaly select defaul interface (wlan,eth, ...)
- Add condition on formatNumber() in case variable number is undefined
i dont know how to fork or anything. So here the updated repo
https://github.com/frankeu/monitor-vps

**Comment by MichaelBelgium** [comment]
Depending on your OS you might need to change the commands (in `getData.php`) for it to work
